import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { AreaChart, BookOpen, Newspaper } from "lucide-react";

/**
 * PetroCast Footer
 * Professional 3-column layout: brand identity | navigation | legal notice
 */
const Footer = () => {
  return (
    <footer className="relative border-t border-white/6 bg-pc-surface/60 backdrop-blur-sm mt-auto">
      {/* Top accent line */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-pc-gold/30 to-transparent" />

      <div className="max-w-7xl mx-auto px-5 sm:px-8 md:px-10 py-14">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-10 md:gap-12">

          {/* ── Brand Column ── */}
          <div>
            <div className="flex items-center gap-2.5 mb-4">
              <div className="w-8 h-8 rounded-[9px] bg-pc-gold flex items-center justify-center shadow-sm shadow-pc-gold/25">
                <span className="font-display font-black text-[13px] text-black">P</span>
              </div>
              <div>
                <span className="block font-display font-bold text-[16px] text-gradient-gold">PetroCast</span>
                <span className="block text-[9px] uppercase tracking-[0.22em] text-text-muted font-medium">Global Intelligence</span>
              </div>
            </div>
            <p className="text-text-muted text-sm leading-relaxed max-w-xs">
              AI-powered crude oil price forecasting platform. Built for professionals, governments, and researchers who require
              institutional-grade analytical tools.
            </p>

            <div className="mt-5 flex items-center gap-2">
              <motion.div
                animate={{ scale: [1, 1.25, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
                className="w-2 h-2 rounded-full bg-pc-green shadow-sm shadow-pc-green/50"
              />
              <span className="text-[11px] text-text-muted font-medium">Models Active</span>
            </div>
          </div>

          {/* ── Navigation Column ── */}
          <div>
            <h4 className="label-xs mb-5">Platform</h4>
            <div className="flex flex-col gap-2.5">
              {[
                { label: "Home",          path: "/",          icon: <span className="w-3.5 h-3.5" /> },
                { label: "Live Dashboard",path: "/dashboard", icon: <AreaChart size={13} /> },
                { label: "Market News",   path: "/news",      icon: <Newspaper size={13} /> },
                { label: "Methodology",   path: "/about",     icon: <BookOpen size={13} /> },
              ].map((link) => (
                <Link
                  key={link.path}
                  to={link.path}
                  className="flex items-center gap-2 text-text-muted hover:text-text-primary text-sm transition-colors duration-150 group w-fit"
                >
                  <span className="text-text-faint group-hover:text-pc-gold transition-colors duration-150">
                    {link.icon}
                  </span>
                  {link.label}
                </Link>
              ))}
            </div>
          </div>

          {/* ── Disclaimer Column ── */}
          <div>
            <h4 className="label-xs mb-5">Legal Notice</h4>
            <div className="space-y-3 text-[12px] text-text-muted leading-relaxed">
              <p>
                Price forecasts are generated by machine learning models and represent probabilistic projections,
                not guaranteed outcomes.
              </p>
              <p>
                This platform is designed for research and analytical purposes. Forecasts should not be used as
                the sole basis for financial, trading, or policy decisions.
              </p>
              <p className="text-text-faint">
                Past model performance does not guarantee future results.
              </p>
            </div>
          </div>
        </div>

        {/* ── Bottom Bar ── */}
        <div className="mt-10 pt-6 border-t border-white/5 flex flex-col sm:flex-row items-center justify-between gap-3">
          <p className="text-[11px] text-text-muted">
            © 2026 PetroCast · Final Year Research Project · All rights reserved
          </p>
          <div className="flex items-center gap-4 text-[11px] text-text-faint">
            <span>Brent · WTI · OPEC · Dubai</span>
            <span className="text-white/10">|</span>
            <span>v10.0</span>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
